# Generated by Django 4.2.11 on 2024-05-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='abbrevation',
            field=models.CharField(default='', max_length=10),
        ),
    ]
